### ISSUE TITLE
not worked on TamperMonkey in edge browser

### ISSUE THREAD

**Issue by bugbounted** [Legend-Master/YouTube-Subtitle-Auto-Switcher#1]
Hi [Legend-Master](https://github.com/Legend-Master),
not worked on TamperMonkey in edge browser & if it's possible make new branch or version for persian(farsi) language.
waiting for oyur commit/s.
finest regards

**Comment by Legend-Master** [comment]
I just tested it on Microsoft Edge (v103.0.1264.49) (Tampermonkey v4.6.1), it worked without any problem, not sure about that, and about other languages, should I openup a branch for every priority list? Maybe let people fork it and make their own adjudgements...

**Comment by Legend-Master** [comment]
I'm closing the issue since you're not responding for 10 days, feel free to comment if you got something to say
